language: python
python:
  - "3.4"
  - "3.5"
services:
  - mongodb
install:
  - "BUILD_LIB=1 pip install ssdeep" # Install ssdeep with included library to fix build error
  - "pip install -r requirements.txt"
script:
  - "CONFIG_PATH=mass_flask_config.config_testing.TestingConfig nosetests"
