language: python
python:
  - "3.4"
  - "3.5"
services:
  - mongodb
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "git submodule init && git submodule update"
# command to run tests
script: nosetests
