language: python
python:
  - "3.4"
  - "3.5"
services:
  - mongodb
install:
  - "pip install -r requirements.txt"
  - "git submodule init && git submodule update"
script:
  - "CONFIG_PATH=mass_flask_config.config_testing.TestingConfig nosetests"
